### PR TITLE
AddedUserRegFormAndSavedToDB

### PR DESCRIPTION
**Pull request by BradCowart**
Testing
  load form
  enter data
  click save
  check that data appears in database.json

### CODE REVIEW

**Review by mjmccann90 — APPROVED** [review]
👍🏻

**Review by ghost — APPROVED** [review]
💯 approved.  works when i input information

**Comment by Hellowalls1** [comment]
Looks good Brad. Checked to make sure the functionality of the form works properly.

**Review by DanielFuqua — APPROVED** [review]
👍

**Pull request merged**
